### ISSUE TITLE
Caption track download broken

### ISSUE THREAD

**Issue by 111100001** [h0lg/SubTubular#10]
it is not retrieving any cc data. only keywords. i have the latest version.

this works: 
![image](https://github.com/user-attachments/assets/8c6c0fff-cb0a-44a1-a31a-e42e31012d40)

this doesn't:

![image](https://github.com/user-attachments/assets/9d7299ba-5c9f-43ab-babb-caa08a06b18d)

**Comment by h0lg** [comment]
@111100001 Thanks for the report - your analysis was correct! The caption track download failed with the older YoutubeExplode version and updating to the current version fixed it. Please update to [v3.1.1](https://github.com/h0lg/SubTubular/releases/tag/v3.1.1) to fix the issue.

You'll also want to **clear your video caches and maybe indexes** because the current version doesn't try to re-download caption tracks if the initial download failed. Look into the `clear-cache` command or use `open cache` to do it manually in a file explorer.
